# Generated by Django 5.0.4 on 2024-04-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
