# Generated by Django 5.0.4 on 2024-05-02 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0002_sensor_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('max_volume', models.IntegerField()),
                ('port', models.IntegerField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pFIONA_sensors.sensor')),
            ],
            options={
                'db_table': 'pfiona_reagent',
            },
        ),
    ]
