# Generated by Django 5.0.4 on 2024-05-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0003_reagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='port',
            field=models.IntegerField(null=True),
        ),
    ]
