# Generated by Django 5.0.4 on 2024-05-08 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0004_alter_reagent_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wait', models.IntegerField()),
            ],
            options={
                'db_table': 'pfiona_reactions',
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='actual_reaction_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pFIONA_sensors.reaction'),
        ),
    ]
