# Generated by Django 5.0.4 on 2024-05-08 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0005_reaction_sensor_actual_reaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeToAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pFIONA_sensors.reaction')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pFIONA_sensors.reagent')),
            ],
            options={
                'db_table': 'pfiona_volumetoadd',
            },
        ),
    ]
