# Generated by Django 5.0.4 on 2024-05-08 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0006_volumetoadd'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reaction',
            table='pfiona_reaction',
        ),
    ]
