# Generated by Django 5.0.4 on 2024-05-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0007_alter_reaction_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumetoadd',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
