# Generated by Django 5.0.4 on 2024-05-09 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0008_volumetoadd_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='standard_concentration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reaction',
            name='standard_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pFIONA_sensors.reagent'),
        ),
    ]
