# Generated by Django 5.0.4 on 2024-05-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0009_reaction_standard_concentration_reaction_standard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='isStandard',
            field=models.BooleanField(default=False),
        ),
    ]
