# Generated by Django 5.0.4 on 2024-05-13 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0012_rename_standard_id_reaction_standard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrumType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pfiona_spectrumtype',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'pfiona_time',
            },
        ),
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pFIONA_sensors.sensor')),
                ('spectrum_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pFIONA_sensors.spectrumtype')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pFIONA_sensors.time')),
            ],
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('wavelength', models.FloatField()),
                ('spectrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pFIONA_sensors.spectrum')),
            ],
            options={
                'db_table': 'pfiona_values',
                'unique_together': {('spectrum', 'wavelength')},
            },
        ),
    ]
