# Generated by Django 5.0.4 on 2024-05-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0013_spectrumtype_time_spectrum_values'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='spectrum',
            table='pfiona_spectrum',
        ),
    ]
