# Generated by Django 5.0.4 on 2024-05-13 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0014_alter_spectrum_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Values',
            new_name='Value',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='standard',
            new_name='standard_id',
        ),
        migrations.RenameField(
            model_name='reagent',
            old_name='sensor',
            new_name='pfiona_sensor_id',
        ),
        migrations.RenameField(
            model_name='spectrum',
            old_name='sensor',
            new_name='pfiona_sensor_id',
        ),
        migrations.RenameField(
            model_name='spectrum',
            old_name='spectrum_type',
            new_name='pfiona_spectrum_type_id',
        ),
        migrations.RenameField(
            model_name='spectrum',
            old_name='time',
            new_name='pfiona_time_id',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='spectrum',
            new_name='pfiona_spectrum_id',
        ),
        migrations.RenameField(
            model_name='volumetoadd',
            old_name='reaction',
            new_name='pfiona_reaction_id',
        ),
        migrations.RenameField(
            model_name='volumetoadd',
            old_name='reagent',
            new_name='pfiona_reagent_id',
        ),
        migrations.AlterUniqueTogether(
            name='value',
            unique_together={('pfiona_spectrum_id', 'wavelength')},
        ),
        migrations.AlterModelTable(
            name='value',
            table='pfiona_value',
        ),
    ]
