# Generated by Django 5.0.4 on 2024-05-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0015_rename_values_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='standard_id',
            new_name='standard',
        ),
        migrations.RenameField(
            model_name='reagent',
            old_name='pfiona_sensor_id',
            new_name='pfiona_sensor',
        ),
        migrations.RenameField(
            model_name='spectrum',
            old_name='pfiona_sensor_id',
            new_name='pfiona_sensor',
        ),
        migrations.RenameField(
            model_name='spectrum',
            old_name='pfiona_spectrum_type_id',
            new_name='pfiona_spectrum_type',
        ),
        migrations.RenameField(
            model_name='spectrum',
            old_name='pfiona_time_id',
            new_name='pfiona_time',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='pfiona_spectrum_id',
            new_name='pfiona_spectrum',
        ),
        migrations.RenameField(
            model_name='volumetoadd',
            old_name='pfiona_reaction_id',
            new_name='pfiona_reaction',
        ),
        migrations.RenameField(
            model_name='volumetoadd',
            old_name='pfiona_reagent_id',
            new_name='pfiona_reagent',
        ),
    ]
