# Generated by Django 5.0.4 on 2024-05-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0017_rename_max_volume_reagent_volume_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='volume_max',
            field=models.IntegerField(null=True),
        ),
    ]
