# Generated by Django 5.0.4 on 2024-05-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0018_alter_reagent_volume_alter_reagent_volume_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_states',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
