# Generated by Django 5.0.4 on 2024-05-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0019_sensor_last_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='volumetoadd',
            unique_together={('pfiona_reaction', 'pfiona_reagent')},
        ),
    ]
