# Generated by Django 5.0.4 on 2024-05-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0021_rename_pfiona_spectrum_type_spectrum_pfiona_spectrumtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('pfiona_reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pFIONA_sensors.reaction')),
                ('pfiona_reagent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pFIONA_sensors.reagent')),
            ],
            options={
                'db_table': 'pfiona_step',
                'unique_together': {('pfiona_reaction', 'pfiona_reagent')},
            },
        ),
        migrations.DeleteModel(
            name='VolumeToAdd',
        ),
    ]
