# Generated by Django 5.0.4 on 2024-05-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0024_remove_reaction_wait'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set(),
        ),
    ]
