# Generated by Django 5.0.4 on 2024-05-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0025_alter_step_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='volume_of_mixture',
            field=models.FloatField(default=0),
        ),
    ]
