# Generated by Django 5.0.4 on 2024-05-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0026_reaction_volume_of_mixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='volume_to_push_to_flow_cell',
            field=models.FloatField(default=0),
        ),
    ]
