# Generated by Django 5.0.4 on 2024-05-21 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0028_alter_sensor_sample_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='WavelengthMonitored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wavelength', models.FloatField()),
                ('pfiona_reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pFIONA_sensors.reagent')),
            ],
            options={
                'db_table': 'pfiona_wavelength_monitored',
            },
        ),
    ]
