# Generated by Django 5.0.4 on 2024-05-21 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0029_wavelengthmonitored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavelengthmonitored',
            name='pfiona_reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pFIONA_sensors.reaction'),
        ),
    ]
