# Generated by Django 5.0.4 on 2024-05-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0030_alter_wavelengthmonitored_pfiona_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='reaction_time',
            field=models.IntegerField(default=30),
        ),
    ]
