# Generated by Django 5.0.4 on 2024-05-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0031_reaction_reaction_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wavelengthmonitored',
            table='pfiona_wavelengthmonitored',
        ),
    ]
