# Generated by Django 5.0.4 on 2024-05-31 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0034_sensor_volume_for_valve_port_priming'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='time_between_2_measure',
            new_name='time_between_2_spectrophotometer_scan',
        ),
    ]
