# Generated by Django 5.0.4 on 2024-06-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0035_rename_time_between_2_measure_sensor_time_between_2_spectrophotometer_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='multi_standard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reaction',
            name='multi_standard_time',
            field=models.IntegerField(default=360),
        ),
        migrations.AddField(
            model_name='reaction',
            name='number_of_blank',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='reaction',
            name='number_of_sample',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='reaction',
            name='number_of_standard',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='standard_concentration',
            field=models.FloatField(default=1),
        ),
    ]
