# Generated by Django 5.0.4 on 2024-06-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0036_reaction_multi_standard_reaction_multi_standard_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='time_between_2_spectrophotometer_scan',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='time_to_wait_for_lamp',
            field=models.FloatField(null=True),
        ),
    ]
