# Generated by Django 5.0.4 on 2024-06-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0037_alter_sensor_time_between_2_spectrophotometer_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='cycle',
            field=models.IntegerField(null=True),
        ),
    ]
