# Generated by Django 5.0.4 on 2024-06-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0038_spectrum_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagent',
            name='volume',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='volume_max',
            field=models.FloatField(null=True),
        ),
    ]
