# Generated by Django 5.0.4 on 2024-06-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0039_alter_reagent_volume_alter_reagent_volume_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='time_to_pump',
            field=models.IntegerField(null=True),
        ),
    ]
