# Generated by Django 5.0.4 on 2024-06-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0040_sensor_time_to_pump'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='deployment',
            field=models.IntegerField(null=True),
        ),
    ]
