# Generated by Django 5.0.4 on 2024-06-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0043_sensor_actual_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='actual_reaction',
            new_name='actual_reactions',
        ),
    ]
