# Generated by Django 5.0.4 on 2024-06-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pFIONA_sensors', '0045_alter_reaction_multi_standard_alter_sensor_sleep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='volume_of_mixture',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='volume_to_push_to_flow_cell',
            field=models.IntegerField(default=0),
        ),
    ]
